#!/usr/bin/env node
/**
 * Reescribe el bloque de métricas del README (test suites, tests, cobertura)
 * a partir de la salida real de Jest, en vez de números escritos a mano.
 *
 * Insumos (generados por `npm run test:metrics`):
 *   - test-results.json          -> jest --json (numTotalTestSuites, numTotalTests)
 *   - coverage/coverage-summary.json -> jest --coverage con reporter json-summary
 *
 * Uso:
 *   node scripts/update-metrics.mjs           # reescribe README.md
 *   node scripts/update-metrics.mjs --check   # no escribe, falla si el
 *                                              # README está desactualizado
 *     (pensado para correr en CI y detectar drift sin necesitar permiso de
 *     commit automático)
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const README_PATH = path.join(ROOT, 'README.md');
const TEST_RESULTS_PATH = path.join(ROOT, 'test-results.json');
const COVERAGE_SUMMARY_PATH = path.join(ROOT, 'coverage', 'coverage-summary.json');

const START_MARKER = '<!-- METRICS:START -->';
const END_MARKER = '<!-- METRICS:END -->';

function readJson(filePath, label) {
  if (!fs.existsSync(filePath)) {
    console.error(
      `[update-metrics] Falta ${label} en ${filePath}. Corré \`npm run test:metrics\` primero.`,
    );
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function buildMetricsBlock() {
  const results = readJson(TEST_RESULTS_PATH, 'test-results.json');
  const coverage = readJson(COVERAGE_SUMMARY_PATH, 'coverage-summary.json');

  const suites = results.numTotalTestSuites;
  const tests = results.numTotalTests;
  const { lines, statements, functions, branches } = coverage.total;

  // Las líneas en blanco justo después de START_MARKER y antes de END_MARKER
  // son deliberadas: Prettier las inserta igual al formatear un HTML comment
  // seguido de una blockquote, así que el template las incluye de entrada —
  // si no, `prettier --check` y `update-metrics --check` divergen para
  // siempre (cada uno "corrige" el README al formato que el otro rechaza).
  return [
    START_MARKER,
    '',
    `> Test status: every implementation ships with a co-located Jest suite —`,
    `> **${suites} suites, ${tests} tests** in total, all passing. Coverage`,
    `> (\`npm run coverage\`, statement/line/function/branch — includes the`,
    `> visualizer: 4 scenes (one per category) plus the player/dom/catalog`,
    `> orchestration have component tests; most of the other 36 scenes still`,
    `> don't, which pulls the overall % down): **${statements.pct}% statements,`,
    `> ${lines.pct}% lines, ${functions.pct}% functions, ${branches.pct}%`,
    `> branches**. Generated by \`scripts/update-metrics.mjs\`, not hand-written.`,
    '',
    END_MARKER,
  ].join('\n');
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const block = buildMetricsBlock();
  const readme = fs.readFileSync(README_PATH, 'utf8');

  const startIdx = readme.indexOf(START_MARKER);
  const endIdx = readme.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1) {
    console.error(`[update-metrics] No encontré ${START_MARKER}/${END_MARKER} en README.md`);
    process.exit(1);
  }

  const before = readme.slice(0, startIdx);
  const after = readme.slice(endIdx + END_MARKER.length);
  const nextReadme = `${before}${block}${after}`;

  if (checkOnly) {
    if (nextReadme !== readme) {
      const oldBlock = readme.slice(startIdx, endIdx + END_MARKER.length);
      console.error('[update-metrics] DIFF DIAGNOSTIC (temporal):');
      console.error('--- README actual ---');
      console.error(JSON.stringify(oldBlock));
      console.error('--- README esperado ---');
      console.error(JSON.stringify(block));
      console.error(
        '[update-metrics] README.md desactualizado respecto a la última corrida de tests/cobertura. Corré `npm run update-metrics` y commiteá el resultado.',
      );
      process.exit(1);
    }
    console.log('[update-metrics] README.md está al día.');
    return;
  }

  fs.writeFileSync(README_PATH, nextReadme, 'utf8');
  console.log('[update-metrics] README.md actualizado.');
}

main();
