#!/usr/bin/env node
/**
 * Reescribe el bloque de métricas del README (test suites, tests, cobertura)
 * a partir de la salida real de Jest, en vez de números escritos a mano.
 *
 * Insumos (generados por `npm run test:metrics`):
 *   - test-results.json          -> jest --json (numTotalTestSuites, numTotalTests)
 *   - coverage/coverage-summary.json -> jest --coverage con reporter json-summary
 *
 * Uso:
 *   node scripts/update-metrics.mjs           # reescribe README.md
 *   node scripts/update-metrics.mjs --check   # no escribe, falla si el
 *                                              # README está desactualizado
 *     (pensado para correr en CI y detectar drift sin necesitar permiso de
 *     commit automático)
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const README_PATH = path.join(ROOT, 'README.md');
const TEST_RESULTS_PATH = path.join(ROOT, 'test-results.json');
const COVERAGE_SUMMARY_PATH = path.join(ROOT, 'coverage', 'coverage-summary.json');

const START_MARKER = '<!-- METRICS:START -->';
const END_MARKER = '<!-- METRICS:END -->';

function readJson(filePath, label) {
  if (!fs.existsSync(filePath)) {
    console.error(
      `[update-metrics] Falta ${label} en ${filePath}. Corré \`npm run test:metrics\` primero.`,
    );
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function buildMetricsBlock() {
  const results = readJson(TEST_RESULTS_PATH, 'test-results.json');
  const coverage = readJson(COVERAGE_SUMMARY_PATH, 'coverage-summary.json');

  const suites = results.numTotalTestSuites;
  const tests = results.numTotalTests;
  const { lines, statements, functions, branches } = coverage.total;

  // Las líneas en blanco justo después de START_MARKER y antes de END_MARKER
  // son deliberadas: Prettier las inserta igual al formatear un HTML comment
  // seguido de una blockquote, así que el template las incluye de entrada —
  // si no, `prettier --check` y `update-metrics --check` divergen para
  // siempre (cada uno "corrige" el README al formato que el otro rechaza).
  return [
    START_MARKER,
    '',
    `> Test status: every implementation ships with a co-located Jest suite —`,
    `> **${suites} suites, ${tests} tests** in total, all passing. Coverage`,
    `> (\`npm run coverage\`, statement/line/function/branch — includes the`,
    `> visualizer: 4 scenes (one per category) plus the player/dom/catalog`,
    `> orchestration have component tests; most of the other 36 scenes still`,
    `> don't, which pulls the overall % down): **${statements.pct}% statements,`,
    `> ${lines.pct}% lines, ${functions.pct}% functions, ${branches.pct}%`,
    `> branches**. Generated by \`scripts/update-metrics.mjs\`, not hand-written.`,
    '',
    END_MARKER,
  ].join('\n');
}

// Tolerancia para las 4 cifras de cobertura al comparar en `--check`. La
// cobertura de FUNCIONES en particular puede variar un poco entre versiones
// de Node (V8/Istanbul cuentan algunas expresiones de función de forma
// distinta) — confirmado real: 74.25% (Node v26 local) vs 73.77% (Node 22.x
// en CI) sobre el MISMO código, mismo commit. Bakear un número exacto que
// tiene que matchear byte-a-byte una corrida fresca en OTRO entorno es
// frágil por diseño; una tolerancia chica separa "el número drifteó porque
// cambió el código" (falla de verdad) de "el número drifteó porque V8 mide
// distinto" (ruido de entorno, no debería tumbar CI).
const COVERAGE_TOLERANCE_PCT = 1.0;

const PCT_LINE_RE =
  /don't, which pulls the overall % down\): \*\*([\d.]+)% statements,\n> ([\d.]+)% lines, ([\d.]+)% functions, ([\d.]+)%\n> branches\*\*/;

function extractPercentages(block) {
  const match = block.match(PCT_LINE_RE);
  if (!match) return null;
  return match.slice(1, 5).map(Number);
}

/** Compara dos bloques de métricas ignorando diferencias de cobertura dentro
 * de COVERAGE_TOLERANCE_PCT puntos porcentuales. El resto del texto (suites,
 * tests, wording) se sigue comparando exacto. */
function blocksMatchWithinTolerance(oldBlock, newBlock) {
  if (oldBlock === newBlock) return true;

  const oldPcts = extractPercentages(oldBlock);
  const newPcts = extractPercentages(newBlock);
  if (!oldPcts || !newPcts) return false;

  // Reemplaza las cifras de cobertura por un placeholder común en ambos
  // bloques; si lo que queda coincide, la única diferencia real eran los %.
  const stripPcts = (block) => block.replace(PCT_LINE_RE, 'PCT_PLACEHOLDER');
  if (stripPcts(oldBlock) !== stripPcts(newBlock)) return false;

  return oldPcts.every((oldPct, i) => Math.abs(oldPct - newPcts[i]) <= COVERAGE_TOLERANCE_PCT);
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const block = buildMetricsBlock();
  const readme = fs.readFileSync(README_PATH, 'utf8');

  const startIdx = readme.indexOf(START_MARKER);
  const endIdx = readme.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1) {
    console.error(`[update-metrics] No encontré ${START_MARKER}/${END_MARKER} en README.md`);
    process.exit(1);
  }

  const before = readme.slice(0, startIdx);
  const after = readme.slice(endIdx + END_MARKER.length);
  const oldBlock = readme.slice(startIdx, endIdx + END_MARKER.length);

  if (checkOnly) {
    if (!blocksMatchWithinTolerance(oldBlock, block)) {
      console.error(
        `[update-metrics] README.md desactualizado respecto a la última corrida de tests/cobertura (fuera de la tolerancia de ±${COVERAGE_TOLERANCE_PCT}pp). Corré \`npm run update-metrics\` y commiteá el resultado.`,
      );
      process.exit(1);
    }
    console.log('[update-metrics] README.md está al día (dentro de tolerancia de cobertura).');
    return;
  }

  const nextReadme = `${before}${block}${after}`;
  fs.writeFileSync(README_PATH, nextReadme, 'utf8');
  console.log('[update-metrics] README.md actualizado.');
}

main();
