#!/usr/bin/env node
/**
 * Reescribe el bloque de métricas del README (test suites, tests, cobertura)
 * a partir de la salida real de Jest, en vez de números escritos a mano.
 *
 * Insumos (generados por `npm run test:metrics`):
 *   - test-results.json          -> jest --json (numTotalTestSuites, numTotalTests)
 *   - coverage/coverage-summary.json -> jest --coverage con reporter json-summary
 *
 * Uso:
 *   node scripts/update-metrics.mjs           # reescribe README.md
 *   node scripts/update-metrics.mjs --check   # no escribe, falla si el
 *                                              # README está desactualizado
 *     (pensado para correr en CI y detectar drift sin necesitar permiso de
 *     commit automático)
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const README_PATH = path.join(ROOT, 'README.md');
const TEST_RESULTS_PATH = path.join(ROOT, 'test-results.json');
const COVERAGE_SUMMARY_PATH = path.join(ROOT, 'coverage', 'coverage-summary.json');
const SCENES_DIR = path.join(ROOT, 'visualizador', 'js', 'scenes');
const TRACE_DIR = path.join(ROOT, 'visualizador', 'js', 'trace');
const CATALOG_PATH = path.join(ROOT, 'visualizador', 'js', 'catalog.js');

const START_MARKER = '<!-- METRICS:START -->';
const END_MARKER = '<!-- METRICS:END -->';

function readJson(filePath, label) {
  if (!fs.existsSync(filePath)) {
    console.error(
      `[update-metrics] Falta ${label} en ${filePath}. Corré \`npm run test:metrics\` primero.`,
    );
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function getRealCounts() {
  const results = readJson(TEST_RESULTS_PATH, 'test-results.json');
  return {
    suites: results.numTotalTestSuites,
    tests: results.numTotalTests,
  };
}

/**
 * Alcance REAL de la verificación del visualizador, derivado del árbol de
 * archivos (no de una frase escrita a mano). Una escena cuenta como cubierta si
 * tiene su test de componente al lado, o si su lógica vive en un módulo de
 * traza con test de equivalencia contra el módulo canónico.
 *
 * Antes estas cifras estaban hardcodeadas en el template y mentían: el bloque
 * afirmaba tests de `player`/`dom` que no existían y hablaba de "the other 36
 * scenes" cuando el catálogo ya tenía 42 escenas. El gate `--check` no podía
 * verlo porque comparaba el bloque generado contra sí mismo.
 */
function getSceneCoverage() {
  const isSource = (f) => f.endsWith('.js') && !f.includes('.test.');
  const sceneModules = fs.readdirSync(SCENES_DIR).filter(isSource);
  const covered = sceneModules.filter((file) => {
    const base = file.replace(/\.js$/, '');
    return (
      fs.existsSync(path.join(SCENES_DIR, `${base}.component.test.js`)) ||
      fs.existsSync(path.join(TRACE_DIR, `${base}.trace.test.mjs`))
    );
  });
  return { sceneModules: sceneModules.length, covered: covered.length };
}

/** Cantidad de escenas publicadas, leída del propio catálogo que sirve la app. */
async function getCatalogSceneCount() {
  const { SCENES } = await import(pathToFileURL(CATALOG_PATH).href);
  return SCENES.length;
}

async function buildMetricsBlock() {
  const { suites, tests } = getRealCounts();
  const coverage = readJson(COVERAGE_SUMMARY_PATH, 'coverage-summary.json');
  const { sceneModules, covered } = getSceneCoverage();
  const catalogScenes = await getCatalogSceneCount();
  const uncovered = sceneModules - covered;

  const { lines, statements, functions, branches } = coverage.total;

  // Las líneas en blanco justo después de START_MARKER y antes de END_MARKER
  // son deliberadas: Prettier las inserta igual al formatear un HTML comment
  // seguido de una blockquote, así que el template las incluye de entrada —
  // si no, `prettier --check` y `update-metrics --check` divergen para
  // siempre (cada uno "corrige" el README al formato que el otro rechaza).
  return [
    START_MARKER,
    '',
    `> Test status: ${suites} suites, ${tests} tests in total, all passing.`,
    `> Scope of the "faithful to the real code" promise: the catalog ships`,
    `> ${catalogScenes} scenes over ${sceneModules} scene modules, and ${covered} of those`,
    `> modules are backed by a test (component test, or trace-equivalence`,
    `> against the canonical module); the other ${uncovered} are not, which is what`,
    `> pulls the overall % down. Coverage (\`npm run coverage\`,`,
    `> statement/line/function/branch): **${statements.pct}% statements,`,
    `> ${lines.pct}% lines, ${functions.pct}% functions, ${branches.pct}%`,
    `> branches**. Generated by \`scripts/update-metrics.mjs\`, not hand-written.`,
    '',
    END_MARKER,
  ].join('\n');
}

// Tolerancia para las 4 cifras de cobertura al comparar en `--check`. La
// cobertura de FUNCIONES en particular puede variar un poco entre versiones
// de Node (V8/Istanbul cuentan algunas expresiones de función de forma
// distinta) — confirmado real: 74.25% (Node v26 local) vs 73.77% (Node 22.x
// en CI) sobre el MISMO código, mismo commit. Bakear un número exacto que
// tiene que matchear byte-a-byte una corrida fresca en OTRO entorno es
// frágil por diseño; una tolerancia chica separa "el número drifteó porque
// cambió el código" (falla de verdad) de "el número drifteó porque V8 mide
// distinto" (ruido de entorno, no debería tumbar CI).
const COVERAGE_TOLERANCE_PCT = 1.0;

const PCT_LINE_RE =
  /statement\/line\/function\/branch\): \*\*([\d.]+)% statements,\n> ([\d.]+)% lines, ([\d.]+)% functions, ([\d.]+)%\n> branches\*\*/;

function extractPercentages(block) {
  const match = block.match(PCT_LINE_RE);
  if (!match) return null;
  return match.slice(1, 5).map(Number);
}

/** Compara dos bloques de métricas ignorando diferencias de cobertura dentro
 * de COVERAGE_TOLERANCE_PCT puntos porcentuales. El resto del texto (suites,
 * tests, wording) se sigue comparando exacto. */
function blocksMatchWithinTolerance(oldBlock, newBlock) {
  if (oldBlock === newBlock) return true;

  const oldPcts = extractPercentages(oldBlock);
  const newPcts = extractPercentages(newBlock);
  if (!oldPcts || !newPcts) return false;

  // Reemplaza las cifras de cobertura por un placeholder común en ambos
  // bloques; si lo que queda coincide, la única diferencia real eran los %.
  const stripPcts = (block) => block.replace(PCT_LINE_RE, 'PCT_PLACEHOLDER');
  if (stripPcts(oldBlock) !== stripPcts(newBlock)) return false;

  return oldPcts.every((oldPct, i) => Math.abs(oldPct - newPcts[i]) <= COVERAGE_TOLERANCE_PCT);
}

// Detecta números de suites/tests escritos a mano FUERA del bloque generado
// (p.ej. "npm test # Jest (25 suites)" en la sección "Running the tests")
// que queden desincronizados del conteo real. El bloque generado es el único
// dueño de esa cifra: cualquier otra mención a mano es, por definición, un
// duplicado que puede driftear (nos pasó: bloque decía 30 suites, la sección
// de abajo decía 25).
const HANDWRITTEN_COUNT_RE = /(\d[\d,]*)\s+(suites?|tests?)\b/gi;

function findHandwrittenDrift(textOutsideBlock, realSuites, realTests) {
  const issues = [];
  let match;
  HANDWRITTEN_COUNT_RE.lastIndex = 0;
  while ((match = HANDWRITTEN_COUNT_RE.exec(textOutsideBlock)) !== null) {
    const value = Number(match[1].replace(/,/g, ''));
    const unit = match[2].toLowerCase();
    const isSuiteUnit = unit.startsWith('suite');
    const expected = isSuiteUnit ? realSuites : realTests;
    if (value !== expected) {
      issues.push(
        `"${match[0]}" dice ${value} pero el conteo real (generado) es ${expected} ${isSuiteUnit ? 'suites' : 'tests'}.`,
      );
    }
  }
  return issues;
}

async function main() {
  const checkOnly = process.argv.includes('--check');
  const block = await buildMetricsBlock();
  const { suites: realSuites, tests: realTests } = getRealCounts();
  const readme = fs.readFileSync(README_PATH, 'utf8');

  const startIdx = readme.indexOf(START_MARKER);
  const endIdx = readme.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1) {
    console.error(`[update-metrics] No encontré ${START_MARKER}/${END_MARKER} en README.md`);
    process.exit(1);
  }

  const before = readme.slice(0, startIdx);
  const after = readme.slice(endIdx + END_MARKER.length);
  const oldBlock = readme.slice(startIdx, endIdx + END_MARKER.length);

  // Corre en ambos modos (--check y escritura normal): un número a mano
  // desincronizado en OTRA sección del README no lo arregla regenerar el
  // bloque, así que hay que frenar y avisar en vez de escribir/pasar en verde.
  const driftIssues = findHandwrittenDrift(before + after, realSuites, realTests);
  if (driftIssues.length > 0) {
    console.error(
      '[update-metrics] Encontré número(s) de tests/suites escritos a mano fuera del bloque generado, desincronizados del conteo real:',
    );
    for (const issue of driftIssues) {
      console.error(`  - ${issue}`);
    }
    console.error(
      '[update-metrics] El bloque generado (METRICS:START/END) es el único dueño de esa cifra. Sacá el número a mano o hacé que referencie el bloque en vez de repetirlo.',
    );
    process.exit(1);
  }

  if (checkOnly) {
    if (!blocksMatchWithinTolerance(oldBlock, block)) {
      console.error(
        `[update-metrics] README.md desactualizado respecto a la última corrida de tests/cobertura (fuera de la tolerancia de ±${COVERAGE_TOLERANCE_PCT}pp). Corré \`npm run update-metrics\` y commiteá el resultado.`,
      );
      process.exit(1);
    }
    console.log('[update-metrics] README.md está al día (dentro de tolerancia de cobertura).');
    return;
  }

  const nextReadme = `${before}${block}${after}`;
  fs.writeFileSync(README_PATH, nextReadme, 'utf8');
  console.log('[update-metrics] README.md actualizado.');
}

await main();
